accounts/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

app_name = 'accounts'

urlpatterns = [
    path('signup/', views.SignUp.as_view(), name='signup'),
    path('login/', auth_views.LoginView.as_view(template_name='accounts/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout')
]

poll_app/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.conf.urls import url
from django.views.generic import RedirectView



urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name='index'),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('polls/', include('polls.urls', namespace='polls')),
    url(r'^favicon\.ico$',RedirectView.as_view(url='/static/images/favicon.ico')),
]

polls/urls.py
from django.urls import path
from . import views

app_name = 'polls'

urlpatterns = [
    path('create/', views.CreatePoll.as_view(), name='create'),
    path('all/', views.PollList.as_view(), name='all'),
    path('vote/<poll_id>/', views.vote, name='vote'),
    path('results/<poll_id>/', views.results, name='results'),
    path('users/<str:username>/', views.UserPollList.as_view(), name='user_poll_list'),
    path('delete/<int:pk>/', views.DeletePoll.as_view(), name='delete')
]

accounts/models.py
from django.db import models

# Create your models here.

polls/models.py
from django.db import models
from django.contrib.auth import get_user_model
from django.urls import reverse
User = get_user_model()

# Create your models here.
class Poll(models.Model):
    question = models.CharField(max_length=200)
    option_one = models.CharField(max_length=50)
    option_two = models.CharField(max_length=50)
    option_three = models.CharField(max_length=50)
    option_one_count = models.IntegerField(default=0)
    option_two_count = models.IntegerField(default=0)
    option_three_count = models.IntegerField(default=0)
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='polls')
    vote_total = models.IntegerField(default=0)

    def get_absolute_url(self):
        return reverse("polls:all")
    
    def __str__(self):
        return self.question

    def total(self):
        return self.option_one_count + self.option_two_count + self.option_three_count
    

accounts/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import get_user_model

class UserCreateForm(UserCreationForm):
    class Meta:
        fields = ('username', 'email', 'password1', 'password2')
        model = get_user_model()

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields["username"].label = "Display name"
        self.fields["email"].label = "Email address"
        self.fields["username"].widget.attrs.update({'class': 'form-control'})
        self.fields["email"].widget.attrs.update({'class': 'form-control'})
        self.fields["password1"].widget.attrs.update({'class': 'form-control'})
        self.fields["password2"].widget.attrs.update({'class': 'form-control'})

polls/forms.py
from django import forms
from .models import Poll

class PollForm(forms.ModelForm):
    class Meta:
        fields = ('question', 'option_one', 'option_two', 'option_three')
        model = Poll

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields["question"].widget.attrs.update({'class': 'form-control'})
        self.fields["option_one"].widget.attrs.update({'class': 'form-control'})
        self.fields["option_two"].widget.attrs.update({'class': 'form-control'})
        self.fields["option_three"].widget.attrs.update({'class': 'form-control'})

accounts/views.py
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import CreateView
from . import forms

# Create your views here.
class SignUp(CreateView):
    form_class = forms.UserCreateForm
    success_url = reverse_lazy('login')
    template_name = 'accounts/signup.html'

poll_app/views.py
from django.shortcuts import render

def index(request):
    return render(request, 'index.html')

polls/views.py
from django.shortcuts import render, redirect
from django.views import generic
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required
from .models import Poll
from . import forms
from django.http import Http404
from django.contrib.auth import get_user_model
User = get_user_model()
from django.urls import reverse_lazy
from django.contrib import messages


# Create your views here.
class CreatePoll(generic.CreateView, LoginRequiredMixin):
    model = Poll
    form_class = forms.PollForm

    def form_valid(self, form):
        self.object = form.save(commit=False)
        self.object.user = self.request.user
        self.object.save()
        return super().form_valid(form)

class PollList(generic.ListView):
    model = Poll
    template_name = 'polls/poll_list.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['polls'] = Poll.objects.all().order_by('-vote_total')
        return context

class UserPollList(generic.ListView, LoginRequiredMixin):
    model = Poll
    template_name = 'polls/user_poll_list.html'

    def get_queryset(self):
        self.poll_user = User.objects.get(username=self.kwargs.get('username'))
        return self.poll_user.polls.all().order_by('-vote_total')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["poll_user"] = self.poll_user 
        context['poll_user_list'] = self.get_queryset()
        return context

class DeletePoll(generic.DeleteView, LoginRequiredMixin):
    model = Poll

    def get_success_url(self):
        return reverse_lazy('polls:user_poll_list', kwargs={'username': self.request.user.username})

    def get_queryset(self):
        queryset = super().get_queryset()
        return queryset.filter(user_id=self.request.user.id)

    def delete(self, *args, **kwargs):
        messages.success(self.request, "Poll Deleted")
        return super().delete(*args, **kwargs)
    

def vote(request, poll_id):
    poll = Poll.objects.get(pk=poll_id)

    if request.method == 'POST':
        selected_option = request.POST.get('inlineRadioOptions')
        if selected_option == 'option1':
            poll.option_one_count += 1
        elif selected_option == 'option2':
            poll.option_two_count += 1
        elif selected_option == 'option3':
            poll.option_three_count += 1
        else:
            raise Http404
        
        poll.vote_total = poll.total()
        poll.save()
        return redirect('polls:all')
    
    context = {'poll': poll}
    return render(request, 'polls/vote.html', context)

@login_required
def results(request, poll_id):
    poll = Poll.objects.get(pk=poll_id)

    context = {'poll': poll}
    return render(request, 'polls/results.html', context)

accounts/templates/accounts/login.html
{% extends 'base.html' %}
{% block content %}

<div class="jumbotron mt-4">
    <h1 class="display-4">Log In</h1>
    <div class="container">
        <form method="POST">
            {% csrf_token %}
            {{form.as_p}}
            <input type="submit" class="btn btn-primary" value="Log In">
        </form>
    </div>
</div>

{% endblock %}

accounts/templates/accounts/signup.html
{% extends 'base.html' %}
{% block content %}

<div class="jumbotron mt-4">
    <h1 class="display-4">Sign Up</h1>
    <div class="container">
        <form method="POST">
            {% csrf_token %}
            {{form.as_p}}
            <input type="submit" class="btn btn-primary" value="Sign Up">
        </form>
    </div>
</div>

{% endblock %}

polls/templates/polls/poll_confirm_delete.html
{% extends "base.html" %}


{% block content %}
<div class="jumbotron mt-4">
	<h3>Are you sure you want to delete this poll?</h3>

	<div class="container mt-3">
		<form method="POST">
			{% csrf_token %}
			<input type="submit" value="Confirm Delete" class="btn btn-danger btn-large">
			<a href="{% url 'polls:user_poll_list' username=user.username %}" class="btn btn-primary btn-large">Cancel</a>
		</form>
	</div>
</div>

{% endblock %}

polls/templates/polls/poll_form.html
{% extends 'base.html' %}

{% block content %}

<div class="jumbotron mt-4">
    <h1 class="display-4">Create Poll</h1>
    <div class="container">
        <form method="POST">
            {% csrf_token %}
            {{form.non_field_errors}}
            <div class="form-group">
                {{form.question.errors}}
                {{form.question.label_tag}}
                {{form.question}}
            </div>
            <div class="d-flex mt-4">
                <div class="form-group mr-4">
                    {{form.option_one.errors}}
                    {{form.option_one.label_tag}}
                    {{form.option_one}}
                </div>
                <div class="form-group mr-4">
                    {{form.option_two.errors}}
                    {{form.option_two.label_tag}}
                    {{form.option_two}}
                </div>
                <div class="form-group">
                    {{form.option_three.errors}}
                    {{form.option_three.label_tag}}
                    {{form.option_three}}
                </div>
            </div>
            <input type="submit" class="btn btn-primary" value="Create Poll">
        </form>
    </div>
</div>

{% endblock %}

polls/templates/polls/poll_list.html
{% extends 'base.html' %}
{% block content %}

<div class="shadow card mt-4 w-75 mr-auto ml-auto">
    <h5 class="card-header">All Polls</h5>
    <ul class="list-group list-group-flush">
        {% for poll in polls %}
            <li class="list-group-item">
                <div class="d-flex">
                    <h6>{{poll.question}}</h6>
                    {% if user != poll.user %}
                        <a href="{% url 'polls:vote' poll.id %}" class="btn btn-primary btn-sm text-white ml-auto">Vote</a>
                        <a href="{% url 'polls:results' poll.id %}" class="btn btn-primary btn-sm text-white ml-2">Results</a>
                    {% else %}
                        <a href="{% url 'polls:results' poll.id %}" class="btn btn-primary btn-sm text-white ml-auto">Results</a>
                    {% endif %}
                </div>
                <div class="d-flex">
                    <a class="" href="{% url 'polls:user_poll_list' username=poll.user.username %}">@{{poll.user.username}}</a>
                    <span class="text-muted ml-auto">{{poll.total}} votes</span>
                </div>
            </li>
        {% endfor %}
    </ul>
</div>

{% endblock %}

polls/templates/polls/results.html
{% extends 'base.html' %}
{% block content %}

<div class="card mt-4 w-75 mr-auto ml-auto">
    <h5 class="card-header">Poll Results</h5>
    <div class="card-body">
        <h5 class="card-title">{{poll.question}}</h5>
        <ul class="list-group list-group-flush">
            <li class="list-group-item">{{poll.option_one}}: {{poll.option_one_count}}</li>
            <li class="list-group-item">{{poll.option_two}}: {{poll.option_two_count}}</li>
            <li class="list-group-item">{{poll.option_three}}: {{poll.option_three_count}}</li>
            <li class="list-group-item"><strong>Total: {{poll.total}}</strong></li>
        </ul>
    </div>
</div>

{% endblock %}

polls/templates/polls/user_poll_list.html
{% extends 'base.html' %}
{% block content %}

<div class="shadow card mt-4 w-75 mr-auto ml-auto">
    <h5 class="card-header">{{poll_user.username}} Poll List</h5>
    <ul class="list-group list-group-flush">
        {% for poll in poll_user_list %}
            <li class="list-group-item">
                <div class="d-flex">
                    <h6>{{poll.question}}</h6>
                    <a href="{% url 'polls:results' poll.id %}" class="btn btn-primary btn-sm text-white ml-auto">Results</a>
                    {% if user == poll_user %}
                        <a href="{% url 'polls:delete' pk=poll.pk %}" class="btn btn-danger btn-sm text-white ml-2">Delete</a>
                    {% else %}
                        <a href="{% url 'polls:vote' poll.id %}" class="btn btn-primary btn-sm text-white ml-2">Vote</a>
                    {% endif %}
                </div>
            </li>
        {% endfor %}
    </ul>
</div>

{% endblock %}

polls/templates/polls/vote.html
{% extends 'base.html' %}
{% block content %}

<div class="card mt-4 w-75 mr-auto ml-auto">
    <h5 class="card-header">Cast your vote</h5>
    <div class="card-body">
        <h5 class="card-title">{{poll.question}}</h5>
        <hr>
        <form method="POST">
            {% csrf_token %}
            <div class="form-group">
                <div class="form-check form-check-inline">
                    <input class="form-check-input" type="radio" name="inlineRadioOptions" id="inlineRadio1" value="option1">
                    <label class="form-check-label" for="inlineRadio1">{{poll.option_one}}</label>
                  </div>
                  <div class="form-check form-check-inline">
                    <input class="form-check-input" type="radio" name="inlineRadioOptions" id="inlineRadio2" value="option2">
                    <label class="form-check-label" for="inlineRadio2">{{poll.option_two}}</label>
                  </div>
                  <div class="form-check form-check-inline">
                    <input class="form-check-input" type="radio" name="inlineRadioOptions" id="inlineRadio3" value="option3">
                    <label class="form-check-label" for="inlineRadio3">{{poll.option_three}}</label>
                  </div>
            </div>
            <input type="submit" class="btn btn-primary" value="Submit">
        </form>
    </div>
</div>

{% endblock %}

templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title></title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <script src="https://kit.fontawesome.com/1b2de11c6b.js" crossorigin="anonymous"></script>
</head>
<body>
    <nav class="navbar bg-primary navbar-dark">
        <div class="container-fluid">
            <a class="navbar-brand" href="{% url 'index' %}">
                <i class="fas fa-poll-h d-inline-block aligm-top"></i>
                Poll App
            </a>
            <div class="container">
                <ul class="nav justify-content-end">
                    {% if user.is_authenticated %}
                        <li class="nav-item">
                            <a class="nav-link text-light" href="{% url 'polls:create' %}">Create Poll</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-light" href="{% url 'polls:all' %}">All Polls</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-light" href="{% url 'polls:user_poll_list' username=user.username %}">Your Polls</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-light" href="{% url 'accounts:logout' %}">Log Out</a>
                        </li>
                    {% else %}
                        <li class="nav-item">
                            <a class="nav-link text-light" href="{% url 'polls:all' %}">All Polls</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-light" href="{% url 'accounts:login' %}">Log In</a>
                        </li>
                        <li class="nav-item">
                            <a class="btn btn-light text-black" href="{% url 'accounts:signup' %}">Sign Up</a>
                        </li>
                    {% endif %}
                </ul>
            </div>
        </div>
    </nav>


    <div class="container">
        {% block content %}
        {% endblock %}
    </div>
    <script src="{% static 'poll_app/js/master.js' %}" type="text/javascript" ></script>
</body>
</html>

templates/index.html
{% extends "base.html" %}
{% block content %}

<div class="jumbotron mt-4">
    <h1 class="display-4">Welcome to the poll app!</h1>
    <p class="lead">This is a simple poll app that lets you vote and create different poles!</p>
    <a class="btn btn-primary" href="{% url 'polls:all' %}">See all polls</a>
</div>

<div class="card-group">
    <div class="card">
        <div class="card-body">
            <h5 class="card-title">Vote</h5>
            <p class="card-text">You can vote for every poll you want!</p>
        </div>
    </div>
    <div class="card">
        <div class="card-body">
            <h5 class="card-title">Create</h5>
            <p class="card-text">Get started by making your own polls with your free accounts!</p>
        </div>
    </div>
    <div class="card">
        <div class="card-body">
            <h5 class="card-title">Results</h5>
            <p class="card-text">See the results for every poll by creating a free account!</p>
        </div>
    </div>
</div>

{% endblock %}